RollForGuild/rollforguild.com

components/AddressInput.js, components/Dropdown.js, pages/groups/create.js
Adds address validation to the group creation page. Verify against acceptance criteria for #38.
=> Group Creation

pages/groups/group.js, scss/pages/_manage-group.scss, store/reducers/groups.js
=> Fix group profiles for non-members

pages/users/user.js, routes.js, scss/app.scss, scss/pages/_user-profile.scss, store/actions/users.js
Basic user profile view with placeholder data to be removed once API features are completed.
This closes #51 and closes #64
=> User Profiles

pages/users/user.js
fixed by not displaying things!
=> Fix user-profile group display

scss/components/_dropdown.scss, scss/components/_input-group.scss
Fix for [WEB-5](https://rollforguild.atlassian.net/browse/WEB-5).
=> fix(Dropdown): Fix shrinking dropdowns

components/Banner.js, components/GroupCard.js, components/GroupProfilePanels/GroupSettingsPanel.js, components/Page.js, components/UserProfilePanels/UserSettingsPanel.js, components/ValidatedInput.js, package.json, pages/_document.js, pages/groups/group.js, pages/groups/search.js, pages/login.js, pages/my/characters.js, pages/register.js, yarn.lock
This is being done so we can have more flexibility with our icons due to how SVG-with-JS limits our capabilities as a react web app.
=> [WEB-41] Migrate to react-fontawesome from SVG-with-JS.

next.config.js
oh well I guess that just works...
If we have to do this again, I'm gonna suggest enabling circle builds for PRs (if we can)
=> [WEB-24] ACTUALLY fix things broken by updates.

components/GroupProfilePanels/GroupSettingsPanel.js
=> [WEB-37] Fix group settings save button (for real this time)

components/UserProfilePanels/UserSettingsPanel.js
=> [WEB-12] Enable user email updating

components/Link.js
=> fix(Link): fix proptypes for link class

components/UserProfilePanels/UserSettingsPanel.js, pages/users/user.js
Also, properly update the user object when user data is submitted.
=> [WEB-65] Notify users to confirm their new email when changing it.

components/Forums/ForumThreadCard.js, pages/forums/view.js, scss/components/_forum-thread-card.scss, scss/components/_pagination.scss
I also fixed some basic styling issues.
=> [WEB-67] Fix thread view titles.

components/AddressInput.js, components/Button.js, components/Dropdown.js, components/GroupProfilePanels/GroupDetailsPanel.js, components/TabPanel.js, docker-compose.yml, next.config.js
also, fixed polling crap to make docker work right. it's actually working now \o/
=> [WEB-79] The "Clapton fixes all the prop problems" PR.

pages/forums/list.js, pages/forums/view.js
Test writing was forgone in this PR as a large amount of work is still needed to support testing pages which is well outside the scope of these tickets
=> [WEB-93] [WEB-94] Fix conditional rendering blocks in forums and forum threads

components/Page.js, pages/groups/group.js, pages/users/user.js, routes.js
Also fixes [WEB-100](https://rollforguild.atlassian.net/browse/WEB-100).
=> [WEB-92][WEB-100] Link group tabs

pages/groups/group.js
=> fix(GroupProfile): remove placeholder 'new event' button.

components/Groups/GroupEventsPanel.js, pages/groups/group.js, store/reducers/events.js
I thought I had committed these changes with the previous PR, but they were still sitting on my main computer when I got on this morning. Whoops!
=> Fix events by using global state to track event objects.

components/Groups/GroupEventCard.js, components/Groups/GroupEventsPanel.js
Also, clarify some wording
and make the delete button a little more friendly.
=> Fix event delete button

components/PageDescription.js, components/PageTitle.js, components/TabPanel.js, components/ValidatedInput.js, jest.config.js, scss/components/_dropdown.scss, scss/components/_profile.scss, scss/components/_tab-panel.scss, scss/components/_validated-input.scss
* Moves profiles to single column view on small screens
* Converts tabs to dropdown on small screens
* Hide unnecessary error icons on `<ValidatedInput />`s
=> [WEB-88] Optimize profiles for mobile

components/Avatar.js, components/Banner.js, components/Nav.js, components/PasswordInput.js, pages/groups/search.js
This PR also fixes a problem with checked and defaultChecked conflicting in the nav for the subnav radio buttons. I just removed defaultChecked entirely since the subnav expansion can persist across pages now.
=> [WEB-136] [WEB-137] [WEB-138] [WEB-139] a11y improvements

components/GroupCard.js, pages/groups/search.js, scss/components/_dropdown.scss, store/actions/groups.js
Also, better prompt the user to create a group when one isn't within close proximity. (~10 miles)
=> [WEB-154] [WEB-155] Add "infinite" search range

pages/groups/group.js
=> Fix Group Page

pages/groups/group.js, store/actions/groups.js
- [[WEB-156](https://rollforguild.atlassian.net/browse/WEB-156)] Limit the number of groups displayed on search pages
=> Release v1.8.9

components/Dropdown.js
This got removed by accident. Oops.
=> fix(Dropdown): Restore Dropdown component
